on:
  release:
    types: 
        - published

name: Bump gitVersion.txt

jobs:
    released:
        runs-on: ubuntu-latest
        steps:
            -   name: Bump gitVersion.txt version
                uses: jaywcjlove/github-action-modify-file-content@main
                with:
                    path: gitVersion.txt
                    body: ${{ github.ref_name }}
                    overwrite: true
                    message: Bump to ${{ github.ref_name }}
                    branch: main